### ISSUE TITLE
Crashes from using ? key to examine inventory while performing actions (e.g. eating)

### ISSUE THREAD

**Issue by potato4444** [SLASHEM-Extended/SLASHEM-Extended#38]
These crashes happen often when I use `?` to examine my inventory contents so I can see which letter corresponds to which item. Haven't managed to get past dlvl4 because of these crashes.

When these crashes happen I am taken to a screen that says "oops..." and a few other things. Then the game exits with the message

    Suddenly, the dungeon collapses.
    
    Report this error to Amy (Bluescreenofdeath at Nethackwiki) so it can be fixed.
    
    You can also contact the admins on the #em.slashem.me IRC channel (Freenode) 
    Report error to "wizard" and it may be possible to rebuild..
    Bad window id 0
    Aborted (core dumped)

Sometimes instead of the window id being 0 it is -256.

Version is master from today built myself. In game claims 2.6.3.

Are there any other details or log files that would be useful to you?

**Comment by AmyBSOD** [comment]
Need more context. Are you playing with the curses interface? Because that is known to be rather crash-prone. If you're playing in tty mode... oh my. In that case I'd have zero idea what is causing that because I've never seen such a bug.

**Comment by potato4444** [comment]
Is the curses interface on by default? How would I check whether I am using it?

**Comment by AmyBSOD** [comment]
Uhh...

The default is tty, so this sounds like the compiling itself went wrong? Maybe Elronnd can help troubleshoot that, because I'm not that knowledgable with unix (which I guess is what you're using, because for Windows there are precompiled binaries). Or you could just play online like everyone else becuase the version on the server is known to not crash :P

**Comment by potato4444** [comment]
I ran it under Valgrind which may or may not be helpful to you. Here is the output:

```
[potato44@YuYuYu slex-2.6.3]$ valgrind ./slex
==12762== Memcheck, a memory error detector
==12762== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==12762== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==12762== Command: ./slex
==12762== 

Suddenly, the dungeon collapses.

Report this error to Amy (Bluescreenofdeath at Nethackwiki) so it can be fixed.

You can also contact the admins on the #em.slashem.me IRC channel (Freenode)
Report error to "wizard" and it may be possible to rebuild..
Bad window id 0
==12762== Invalid read of size 4
==12762==    at 0x660621: done (end.c:1055)
==12762==    by 0x666A9B: panic (end.c:543)
==12762==    by 0xF75245: tty_add_menu (wintty.c:3246)
==12762==    by 0x6E6C26: display_pickinv (invent.c:6935)
==12762==    by 0x6E7CDD: getobj (invent.c:5961)
==12762==    by 0x655297: floorfood (eat.c:7238)
==12762==    by 0x655297: doeat (eat.c:6420)
==12762==    by 0x549065: rhack (cmd.c:13508)
==12762==    by 0x433C32: moveloop (allmain.c:10585)
==12762==    by 0x403D98: main (unixmain.c:299)
==12762==  Address 0x4af06e0 is 80 bytes inside a block of size 168 free'd
==12762==    at 0x4838A0C: free (vg_replace_malloc.c:540)
==12762==    by 0xC585E6: saveobjchn (save.c:1343)
==12762==    by 0xC58D7C: savegamestate (save.c:754)
==12762==    by 0xC59173: dosave0.part.3 (save.c:314)
==12762==    by 0x666AE6: panic (end.c:526)
==12762==    by 0xF75245: tty_add_menu (wintty.c:3246)
==12762==    by 0x6E6C26: display_pickinv (invent.c:6935)
==12762==    by 0x6E7CDD: getobj (invent.c:5961)
==12762==    by 0x655297: floorfood (eat.c:7238)
==12762==    by 0x655297: doeat (eat.c:6420)
==12762==    by 0x549065: rhack (cmd.c:13508)
==12762==    by 0x433C32: moveloop (allmain.c:10585)
==12762==    by 0x403D98: main (unixmain.c:299)
==12762==  Block was alloc'd at
==12762==    at 0x4839B1A: calloc (vg_replace_malloc.c:762)
==12762==    by 0x4687A5: alloc (alloc.c:59)
==12762==    by 0xA2AEED: mksobj (mkobj.c:1843)
==12762==    by 0xDD09D9: ini_inv (u_init.c:29208)
==12762==    by 0xDEF188: u_init (u_init.c:12904)
==12762==    by 0x41B623: newgame (allmain.c:10803)
==12762==    by 0x403D75: main (unixmain.c:291)
==12762== 
==12762== 
==12762== Process terminating with default action of signal 6 (SIGABRT): dumping core
==12762==    at 0x490857F: raise (in /usr/lib64/libc-2.28.so)
==12762==    by 0x48F2894: abort (in /usr/lib64/libc-2.28.so)
==12762==    by 0x403A63: panic.cold.6 (end.c:487)
==12762==    by 0xF75CE0: tty_curs (wintty.c:2806)
==12762==    by 0x4B5A8B: botl_player (botl.c:370)
==12762==    by 0x4B5F90: bot1str (botl.c:454)
==12762==    by 0x571972: dump_screen (display.c:2320)
==12762==    by 0x661D38: done (end.c:1525)
==12762==    by 0x666A9B: panic (end.c:543)
==12762==    by 0xF75245: tty_add_menu (wintty.c:3246)
==12762==    by 0x6E6C26: display_pickinv (invent.c:6935)
==12762==    by 0x6E7CDD: getobj (invent.c:5961)
==12762== 
==12762== HEAP SUMMARY:
==12762==     in use at exit: 229,620 bytes in 148 blocks
==12762==   total heap usage: 2,609 allocs, 2,461 frees, 674,272 bytes allocated
==12762== 
==12762== LEAK SUMMARY:
==12762==    definitely lost: 440 bytes in 5 blocks
==12762==    indirectly lost: 7,006 bytes in 109 blocks
==12762==      possibly lost: 0 bytes in 0 blocks
==12762==    still reachable: 222,174 bytes in 34 blocks
==12762==         suppressed: 0 bytes in 0 blocks
==12762== Rerun with --leak-check=full to see details of leaked memory
==12762== 
==12762== For lists of detected and suppressed errors, rerun with: -s
==12762== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Aborted (core dumped)
```

This one was from me trying to eat. The last one I mentioned on IRC was from trying to apply an object.

**Comment by AmyBSOD** [comment]
So it's failing to draw a window. Weird... I've never seen that error before.

**Comment by potato4444** [comment]
Here are some more crashes, same general idea, they happen when i press `?` at a prompt. But they play out slightly differently.

[engrave.txt](https://github.com/SLASHEM-Extended/SLASHEM-Extended/files/4181368/engrave.txt)
[eat.txt](https://github.com/SLASHEM-Extended/SLASHEM-Extended/files/4181370/eat.txt)

**Comment by potato4444** [comment]
Just in case it matters (but I hope it doesn't) the first log and engrave.txt were done with DECgraphics on. eat.txt had DECgraphics off.

**Comment by potato4444** [comment]
Here is another crash that again looks slightly different. The last actions I did were picking up a tripe ration off the floor. Then trying to use `?` at the eat prompt. Not sure if they are directly connected as far as the crash is concerned.
[tripe.txt](https://github.com/SLASHEM-Extended/SLASHEM-Extended/files/4181999/tripe.txt)

**Comment by potato4444** [comment]
I have a game caught mid-crash open in a debugger at the moment. For this particular crash the `type` of a window is wrong.

This is the particular part that has failed in this crash:

https://github.com/SLASHEM-Extended/SLASHEM-Extended/blob/5210d02842e7716941d1a96c8269f358b3c69616/win/tty/wintty.c#L3245

The value of `cw->type` should be 4(`NHW_MENU`), but it for some reason is 6. I don't think 6 even corresponds to a valid type.

Here is the backtrace to go along with it

```
#0  tty_add_menu (window=window@entry=0, glyph=glyph@entry=404586, 
    identifier=identifier@entry=0x7fff8e0fa2f0, ch=ch@entry=0 '\000', 
    gch=gch@entry=0 '\000', attr=7, str=0x3bf4a30 "Comestibles", preselected=0)
    at win/tty/wintty.c:3246
#1  0x00000000006e6d07 in display_pickinv (lets=<optimized out>, 
    want_reply=want_reply@entry=1, out_cnt=out_cnt@entry=0x0, 
    want_dump=want_dump@entry=0) at src/invent.c:6935
#2  0x00000000006e7dbe in getobj (
    let=0x100a0d2 <allobj+2> "\002\003\t\n\f\004\005\006\b\a\016\017\020\021\v", word=<optimized out>, word@entry=0x141a243 "eat") at src/invent.c:5809
#3  0x0000000000655298 in floorfood (verb=0x141a243 "eat") at src/eat.c:7238
#4  doeat () at src/eat.c:6420
#5  0x0000000000549066 in rhack (cmd=<optimized out>, cmd@entry=0x0)
    at src/cmd.c:13508
#6  0x0000000000433c33 in moveloop () at src/allmain.c:10585
#7  0x0000000000403d99 in main (argc=<optimized out>, argv=<optimized out>)
    at sys/unix/unixmain.c:299
```

**Comment by potato4444** [comment]
Found in wintty.h that 6 is `NHW_BASE`. So this is an actual window type. Now I've realised that `BASE_WINDOW` and  the `win` variable in `display_pickinv` are both 0. Somehow they have ended up as the same `winid`.

**Comment by AmyBSOD** [comment]
Doesn't seem to happen on the server, nor does it happen with my local Windows copy; chances are the compilation has gone wrong in some way.
